<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Evaluaci&oacute;n de cambio clim&aacute;tico</h2></div><div class="iso-panel-body"><strong>Relevante para el SGC:</strong> {{ is_null($periodo->cambio_climatico_relevante)?'Pendiente':($periodo->cambio_climatico_relevante?'S&iacute;':'No') }}<p class="mb-0 mt-2">{{ $periodo->fundamento_cambio_climatico ?: 'Sin fundamento registrado.' }}</p></div></div>

<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Contexto FODA y cobertura</h2></div><div class="table-responsive"><table class="table iso-table mb-0"><thead><tr><th>Elemento</th><th>Identificaci&oacute;n</th><th>Fuente / fundamento</th><th>Evaluaci&oacute;n y decisi&oacute;n</th><th>Tratamientos derivados</th></tr></thead><tbody>
@forelse($periodo->contextos as $contexto)<tr><td><strong>{{ $contexto->codigo }} &mdash; {{ ucfirst($contexto->tipo) }}</strong><div>{{ $contexto->titulo }}</div></td><td>{{ $contexto->descripcion }}<div class="mt-1"><small>{{ $contexto->fecha_identificacion?->format('d/m/Y') }} &middot; {{ $contexto->proceso ?: 'Sin proceso' }} &middot; {{ $contexto->responsable?->name ?? 'Sin responsable' }}</small></div></td><td><strong>{{ $contexto->fuente_tipo ?: 'Sin tipo de fuente' }}</strong><div>{{ $contexto->fuente ?: 'Sin fundamento' }}</div>@if($contexto->referencia_existente)<small>Referencia: {{ $contexto->referencia_existente }}</small>@endif</td><td>Relevante: {{ is_null($contexto->relevante_sgc)?'Pendiente':($contexto->relevante_sgc?'S&iacute;':'No') }}<div><strong>{{ ucfirst(str_replace('_',' ',$contexto->decision)) }}</strong></div><div>{{ $contexto->justificacion }}</div></td><td>@forelse($contexto->riesgos as $riesgo)<a href="{{ route('planificacion.riesgos.show',$riesgo) }}"><strong>{{ $riesgo->codigo }}</strong></a> &middot; {{ ucfirst($riesgo->tipo) }} &middot; {{ ucfirst(str_replace('_',' ',$riesgo->estado)) }}@unless($loop->last)<br>@endunless @empty Sin registro derivado @endforelse</td></tr>@empty<tr><td colspan="5">Sin elementos FODA.</td></tr>@endforelse
</tbody></table></div></div>

<div class="report-page-break"></div>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Riesgos, oportunidades, acciones y eficacia</h2></div><div class="iso-panel-body">
@forelse($periodo->riesgos as $riesgo)
    <div class="report-detail-card">
        <div class="d-flex justify-content-between gap-3"><div><a href="{{ route('planificacion.riesgos.show',$riesgo) }}"><strong>{{ $riesgo->codigo }} &mdash; {{ ucfirst($riesgo->tipo) }}</strong></a><h3 class="h6 mt-1">{{ $riesgo->identificacion }}</h3></div><span class="report-status">{{ ucfirst(str_replace('_',' ',$riesgo->estado)) }}</span></div>
        <div class="row"><div class="col-md-6"><span class="report-label">Origen</span><div>@if($riesgo->contexto)<a href="{{ route('planificacion.foda.show',$riesgo->contexto) }}">{{ $riesgo->contexto->codigo }} &mdash; {{ $riesgo->contexto->titulo }}</a>@else Registro independiente @endif</div></div><div class="col-md-3"><span class="report-label">Proceso</span><div>{{ $riesgo->proceso }}</div></div><div class="col-md-3"><span class="report-label">Responsable</span><div>{{ $riesgo->responsable?->name ?? 'Sin asignar' }}</div></div></div>
        <div class="row mt-2"><div class="col-md-6"><span class="report-label">Efecto potencial</span><div>{{ $riesgo->efecto_potencial }}</div></div><div class="col-md-6"><span class="report-label">Criterio de eficacia</span><div>{{ $riesgo->criterio_eficacia }}</div></div></div>
        <div class="mt-2"><strong>Valoraci&oacute;n:</strong> inicial {{ $riesgo->impacto_inicial }} &times; {{ $riesgo->probabilidad_inicial }} = {{ $riesgo->indice_inicial }}@if($riesgo->indice_final) &middot; actual/final {{ $riesgo->impacto_final }} &times; {{ $riesgo->probabilidad_final }} = {{ $riesgo->indice_final }}@endif &middot; pr&oacute;xima revisi&oacute;n {{ $riesgo->fecha_verificacion_prevista?->format('d/m/Y') ?? 'sin programar' }}</div>
        @if($riesgo->origenContinuidad || $riesgo->continuidades->isNotEmpty())<div class="mt-2"><strong>Continuidad:</strong> @if($riesgo->origenContinuidad)<a href="{{ route('planificacion.riesgos.show',$riesgo->origenContinuidad) }}">proviene de {{ $riesgo->origenContinuidad->codigo }} ({{ $riesgo->origenContinuidad->periodo?->anio }})</a>@endif @foreach($riesgo->continuidades as $continuidad) &middot; <a href="{{ route('planificacion.riesgos.show',$continuidad) }}">contin&uacute;a como {{ $continuidad->codigo }} ({{ $continuidad->periodo?->anio }})</a>@endforeach</div>@endif
        <hr><strong>Acciones y evidencias</strong>
        @forelse($riesgo->acciones as $accion)<div class="mt-2 pl-2 border-left"><strong>{{ $accion->descripcion }}</strong> &mdash; {{ ucfirst(str_replace('_',' ',$accion->estado)) }}<div><small>{{ $accion->responsable?->name ?? 'Sin responsable' }} &middot; Objetivo {{ $accion->fecha_objetivo?->format('d/m/Y') }}</small></div>@if($accion->resultado)<div>Resultado: {{ $accion->resultado }}</div>@endif
            @foreach($accion->seguimientos as $seguimiento)<div><small>{{ $seguimiento->fecha->format('d/m/Y') }} &middot; {{ $seguimiento->detalle }} @if($seguimiento->documento)&middot; @include('iso.informes._documento',['documento'=>$seguimiento->documento])@endif @if($seguimiento->enlace_externo)&middot; <a href="{{ $seguimiento->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a>@endif</small></div>@endforeach
            @foreach($accion->transiciones as $transicion)<div><small>Reapertura/cambio: {{ ucfirst(str_replace('_',' ',$transicion->estado_anterior)) }} &rarr; {{ ucfirst(str_replace('_',' ',$transicion->estado_nuevo)) }} &middot; {{ $transicion->motivo }} &middot; {{ $transicion->realizadoPor?->name ?? 'Usuario no disponible' }}</small></div>@endforeach
        </div>@empty<div class="text-muted">Sin acciones registradas.</div>@endforelse
        <hr><strong>Historial de evaluaciones de eficacia</strong>
        @forelse($riesgo->verificaciones as $verificacion)<div class="mt-2 pl-2 border-left"><strong>{{ $verificacion->fecha->format('d/m/Y') }} &middot; @if($verificacion->tipo==='final') Evaluaci&oacute;n de eficacia @else Seguimiento @endif &middot; Eficacia {{ ucfirst($verificacion->eficacia) }}</strong><div>{{ $verificacion->conclusion }}</div><small>Valoraci&oacute;n {{ $verificacion->impacto }} &times; {{ $verificacion->probabilidad }} = {{ $verificacion->indice }} &middot; Decisi&oacute;n: {{ ucfirst(str_replace('_',' ',$verificacion->estado_resultante)) }} &middot; {{ $verificacion->verificador?->name ?? 'Sin verificador' }}</small>@if($verificacion->justificacion_excepcion)<div><small>Justificaci&oacute;n: {{ $verificacion->justificacion_excepcion }}</small></div>@endif @if($verificacion->documento)<div><small>@include('iso.informes._documento',['documento'=>$verificacion->documento])</small></div>@endif @if($verificacion->enlace_externo)<div><small><a href="{{ $verificacion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></small></div>@endif</div>@empty<div class="text-muted">Sin evaluaciones de eficacia registradas.</div>@endforelse
    </div>
@empty<div class="text-muted">Sin riesgos u oportunidades.</div>@endforelse
</div></div>

@include('iso.informes._objetivos')

<div class="report-page-break"></div>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Partes interesadas y evaluaci&oacute;n peri&oacute;dica</h2></div><div class="iso-panel-body">
@forelse($partes as $parte)
    @php($evaluacion=$parte->evaluaciones->first())
    <div class="report-detail-card">
        <div class="d-flex justify-content-between"><strong>{{ $parte->nombre }}</strong><span class="report-status {{ $evaluacion?'ok':'warn' }}">{{ $evaluacion?'Evaluada en '.$periodo->anio:'Pendiente en '.$periodo->anio }}</span></div>
        <div class="row mt-2"><div class="col-md-6"><span class="report-label">Necesidades / requisitos</span><div>{{ $parte->necesidades_requisitos }}</div></div><div class="col-md-3"><span class="report-label">Responsabilidad</span><div>{{ $parte->area_responsable ?: 'Sin area' }} &middot; {{ $parte->responsable?->name ?? 'Sin responsable' }}</div></div><div class="col-md-3"><span class="report-label">Clima</span><div>{{ is_null($parte->requisitos_climaticos)?'Pendiente':($parte->requisitos_climaticos?'Con requisitos':'No identificados') }}</div></div></div>
        <div class="mt-2"><span class="report-label">M&eacute;todo de medici&oacute;n</span><div>{{ $parte->metodo_medicion }}</div></div>
        @if($parte->detalle_climatico)<div class="mt-2"><span class="report-label">Fundamento clim&aacute;tico</span><div>{{ $parte->detalle_climatico }}</div></div>@endif
        @if($evaluacion)
            <hr><strong>{{ $evaluacion->fecha_evaluacion->format('d/m/Y') }} &middot; {{ ucfirst(str_replace('_',' ',$evaluacion->resultado)) }}</strong><div>{{ $evaluacion->observaciones }}</div><small>Evalu&oacute;: {{ $evaluacion->evaluador?->name ?? 'Usuario no disponible' }} &middot; Pr&oacute;xima revisi&oacute;n: {{ $evaluacion->proxima_revision?->format('d/m/Y') ?? 'sin programar' }}</small>
            @if($evaluacion->documento)<div>@include('iso.informes._documento',['documento'=>$evaluacion->documento])</div>@endif
            @if($evaluacion->enlace_externo)<div><a href="{{ $evaluacion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif
            @if($evaluacion->riesgos->isNotEmpty())<div>Riesgos relacionados: @foreach($evaluacion->riesgos as $riesgo)<a href="{{ route('planificacion.riesgos.show',$riesgo) }}">{{ $riesgo->codigo }} &middot; {{ ucfirst(str_replace('_',' ',$riesgo->estado)) }}</a>@if(!$loop->last), @endif @endforeach</div>@endif
        @endif
    </div>
@empty
    <div class="text-muted">Sin partes interesadas aplicables.</div>
@endforelse
</div></div>

<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Proveedores externos y ciclos de evaluaci&oacute;n</h2></div><div class="iso-panel-body">
@forelse($proveedores as $proveedor)<div class="report-detail-card"><div class="d-flex justify-content-between"><div><strong>{{ $proveedor->codigo }} &mdash; {{ $proveedor->nombre }}</strong><div>{{ $proveedor->producto_servicio }}</div></div><span class="report-status {{ $proveedor->criticidad==='critico'?'bad':'' }}">@if($proveedor->criticidad==='critico') Cr&iacute;tico @else No cr&iacute;tico @endif</span></div><div><small>{{ $proveedor->area_responsable }} &middot; Alta {{ $proveedor->fecha_alta?->format('d/m/Y') }} &middot; Evaluaci&oacute;n cada {{ $proveedor->periodicidad_meses }} meses</small></div>
@php($seleccion=$proveedor->selecciones->first())@if($seleccion)<div class="mt-2"><span class="report-label">Selecci&oacute;n vigente al cierre del per&iacute;odo</span><div>{{ $seleccion->fecha->format('d/m/Y') }} &middot; {{ ucfirst(str_replace('_',' ',$seleccion->resultado)) }} &middot; {{ number_format($seleccion->puntaje,2,',','.') }} &middot; {{ $seleccion->evaluador?->name ?? 'Sin evaluador' }}</div><div>{{ $seleccion->conclusion }}</div>@if($seleccion->documento)<div>@include('iso.informes._documento',['documento'=>$seleccion->documento])</div>@endif</div>@else<div class="mt-2 text-muted">Sin selecci&oacute;n registrada hasta el cierre del per&iacute;odo.</div>@endif
<hr><strong>Evaluaciones del per&iacute;odo {{ $periodo->anio }}</strong>@forelse($proveedor->evaluaciones as $evaluacion)<div class="mt-2 pl-2 border-left"><strong>{{ $evaluacion->fecha_evaluacion->format('d/m/Y') }} &middot; @if($evaluacion->tipo==='reevaluacion') Reevaluaci&oacute;n @else Evaluaci&oacute;n peri&oacute;dica @endif &middot; {{ ucfirst(str_replace('_',' ',$evaluacion->resultado)) }}</strong><div>Puntaje {{ number_format($evaluacion->puntaje,2,',','.') }} &middot; Decisi&oacute;n {{ ucfirst(str_replace('_',' ',$evaluacion->decision)) }} &middot; Ciclo {{ ucfirst(str_replace('_',' ',$evaluacion->estado_ciclo)) }}</div>@if(filled($evaluacion->calificaciones))<div><small><strong>Calificaciones:</strong> @foreach($evaluacion->calificaciones as $criterio=>$valor){{ ucfirst(str_replace('_',' ',$criterio)) }}: {{ $valor }}@unless($loop->last) &middot; @endunless @endforeach</small></div>@endif<div>{{ $evaluacion->conclusion }}</div>@if($evaluacion->justificacion)<div>Justificaci&oacute;n: {{ $evaluacion->justificacion }}</div>@endif<small>Evalu&oacute;: {{ $evaluacion->evaluador?->name ?? 'Usuario no disponible' }} &middot; Pr&oacute;xima: @if($evaluacion->proxima_evaluacion){{ $evaluacion->proxima_evaluacion->format('d/m/Y') }}@else sin programar @endif &middot; An&aacute;lisis de riesgo: @if($evaluacion->requiere_analisis_riesgo) S&iacute; @else No @endif</small>@if($evaluacion->documento)<div>@include('iso.informes._documento',['documento'=>$evaluacion->documento])</div>@endif @if($evaluacion->enlace_externo)<div><a href="{{ $evaluacion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif
@foreach($evaluacion->acciones as $accion)<div class="mt-1"><strong>Acci&oacute;n:</strong> {{ $accion->descripcion }} &mdash; {{ ucfirst(str_replace('_',' ',$accion->estado)) }} &middot; {{ $accion->responsable?->name ?? $accion->area_responsable }} &middot; {{ $accion->fecha_objetivo?->format('d/m/Y') }}@if($accion->resultado)<div>Resultado: {{ $accion->resultado }}</div>@endif @if($accion->documento)<div>@include('iso.informes._documento',['documento'=>$accion->documento])</div>@endif @if($accion->enlace_externo)<div><a href="{{ $accion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif</div>@endforeach @if($evaluacion->riesgos->isNotEmpty())<div>Riesgos: @foreach($evaluacion->riesgos as $riesgo)<a href="{{ route('planificacion.riesgos.show',$riesgo) }}">{{ $riesgo->codigo }}</a>@unless($loop->last), @endunless @endforeach</div>@endif</div>@empty<div class="text-muted">Sin evaluaci&oacute;n registrada para {{ $periodo->anio }}.</div>@endforelse</div>@empty<div class="text-muted">Sin proveedores aplicables.</div>@endforelse
</div></div>

<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Historial del per&iacute;odo</h2></div><div class="table-responsive"><table class="table iso-table mb-0"><thead><tr><th>Fecha</th><th>Acci&oacute;n</th><th>Transici&oacute;n</th><th>Motivo</th><th>Usuario / control</th></tr></thead><tbody>@forelse($periodo->transiciones->sortBy('created_at') as $transicion)<tr><td>{{ $transicion->created_at->format('d/m/Y H:i') }}</td><td>{{ ucfirst(str_replace('_',' ',$transicion->accion)) }}</td><td>{{ ucfirst($transicion->estado_anterior) }} &rarr; {{ ucfirst($transicion->estado_nuevo) }}</td><td>{{ $transicion->motivo }}</td><td>{{ $transicion->realizadoPor?->name ?? 'Usuario no disponible' }}@if($transicion->resumen_control)<div><small>@foreach($transicion->resumen_control as $clave=>$valor){{ str_replace('_',' ',$clave) }}: @if(is_bool($valor))@if($valor)S&iacute;@else No @endif @elseif(is_null($valor))&mdash;@else{{ $valor }}@endif @unless($loop->last) &middot; @endunless @endforeach</small></div>@endif</td></tr>@empty<tr><td colspan="5">Sin transiciones registradas.</td></tr>@endforelse</tbody></table></div></div>
