<div class="report-page-break"></div>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Objetivos de calidad, mediciones y evaluaci&oacute;n de cierre</h2></div><div class="iso-panel-body">
@forelse($objetivos as $objetivo)
    @php($indicador=$objetivo->indicadorPrincipal)
    @php($cierre=$objetivo->evaluaciones->firstWhere('tipo','cierre_periodo'))
    <div class="report-detail-card">
        <div class="d-flex justify-content-between gap-3"><div><a href="{{ route('planificacion.objetivos.show',$objetivo) }}"><strong>{{ $objetivo->codigo }} &mdash; {{ $objetivo->titulo }}</strong></a><div>{{ $objetivo->descripcion }}</div></div><div><span class="report-status {{ $objetivo->cumplimiento_actual==='cumplido'?'ok':($objetivo->cumplimiento_actual==='incumplido'?'bad':'warn') }}">{{ ucfirst($objetivo->cumplimiento_actual) }}</span><div class="text-center"><small>{{ ucfirst($objetivo->estado) }}</small></div></div></div>
        <div class="row mt-2"><div class="col-md-4"><span class="report-label">Compromiso de la pol&iacute;tica</span><div>{{ $objetivo->compromiso_politica }}</div></div><div class="col-md-4"><span class="report-label">Proceso / responsabilidad</span><div>{{ $objetivo->proceso }} &middot; {{ $objetivo->area_responsable }} &middot; {{ $objetivo->responsable?->name ?? 'Sin responsable' }}</div></div><div class="col-md-4"><span class="report-label">Planificaci&oacute;n</span><div>{{ $objetivo->fecha_inicio->format('d/m/Y') }} al {{ $objetivo->fecha_objetivo->format('d/m/Y') }} &middot; {{ $objetivo->periodicidad_seguimiento }}</div></div></div>
        @if($indicador)<div class="mt-2"><span class="report-label">Indicador, c&aacute;lculo y meta</span><div><strong>{{ $indicador->nombre }}</strong> &middot; {{ $indicador->metodo_calculo }}</div><div>Meta: {{ str_replace('_',' ',$indicador->comparador) }} {{ $indicador->meta }}@if($indicador->comparador==='rango') a {{ $indicador->meta_hasta }}@endif {{ $indicador->unidad }} &middot; Fuente: {{ $indicador->fuente }} &middot; Frecuencia: {{ $indicador->frecuencia }}</div></div>
        <div class="mt-2"><strong>Mediciones</strong>@forelse($indicador->mediciones->sortBy('fecha_medicion') as $medicion)<div>{{ $medicion->fecha_medicion->format('d/m/Y') }} &middot; {{ $medicion->valor }} {{ $indicador->unidad }}@if($medicion->periodo_referencia) &middot; {{ $medicion->periodo_referencia }}@endif @if($medicion->observaciones)&middot; {{ $medicion->observaciones }}@endif @if($medicion->documento)&middot; @include('iso.informes._documento',['documento'=>$medicion->documento])@endif @if($medicion->enlace_externo)&middot; <a href="{{ $medicion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a>@endif</div>@empty<div class="text-muted">Sin mediciones.</div>@endforelse<div><strong>Resultado calculado:</strong> {{ $objetivo->resultado_actual ?? 'Sin datos' }} @if($objetivo->resultado_actual!==null){{ $indicador->unidad }} &middot; {{ ucfirst($objetivo->cumplimiento_actual) }}@endif</div></div>@else<div class="text-muted mt-2">Sin indicador principal.</div>@endif
        <hr><strong>Acciones y evidencias</strong>@forelse($objetivo->acciones as $accion)<div class="mt-2 pl-2 border-left"><strong>{{ $accion->descripcion }}</strong> &mdash; {{ ucfirst(str_replace('_',' ',$accion->estado)) }}<div><small>{{ $accion->area_responsable }} &middot; {{ $accion->responsable?->name ?? 'Sin responsable' }} &middot; Objetivo {{ $accion->fecha_objetivo->format('d/m/Y') }}</small></div>@if($accion->resultado)<div>Resultado: {{ $accion->resultado }}</div>@endif @if($accion->documento)<div>@include('iso.informes._documento',['documento'=>$accion->documento])</div>@endif @if($accion->enlace_externo)<div><a href="{{ $accion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif @foreach($accion->seguimientos as $seguimiento)<div><small>{{ $seguimiento->fecha->format('d/m/Y') }} &middot; {{ $seguimiento->detalle }} @if($seguimiento->documento)&middot; @include('iso.informes._documento',['documento'=>$seguimiento->documento])@endif @if($seguimiento->enlace_externo)&middot; <a href="{{ $seguimiento->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a>@endif</small></div>@endforeach @foreach($accion->transiciones as $transicion)<div><small>Cambio: {{ ucfirst(str_replace('_',' ',$transicion->estado_anterior)) }} &rarr; {{ ucfirst(str_replace('_',' ',$transicion->estado_nuevo)) }} &middot; {{ $transicion->motivo }} &middot; {{ $transicion->usuario?->name ?? 'Usuario no disponible' }}</small></div>@endforeach</div>@empty<div class="text-muted">Sin acciones.</div>@endforelse
        <hr><strong>Evaluaciones</strong>@forelse($objetivo->evaluaciones as $evaluacion)<div class="mt-2 pl-2 border-left"><strong>{{ $evaluacion->fecha_evaluacion->format('d/m/Y') }} &middot; @if($evaluacion->tipo==='cierre_periodo') Evaluaci&oacute;n de cierre @else Seguimiento peri&oacute;dico @endif &middot; {{ ucfirst($evaluacion->cumplimiento) }}</strong><div>Resultado {{ $evaluacion->resultado }} &middot; Decisi&oacute;n: {{ ucfirst(str_replace('_',' ',$evaluacion->decision)) }}</div><div>{{ $evaluacion->conclusion }}</div>@if($evaluacion->justificacion)<div>Justificaci&oacute;n: {{ $evaluacion->justificacion }}</div>@endif<small>Evalu&oacute;: {{ $evaluacion->evaluadoPor?->name ?? 'Usuario no disponible' }} &middot; Pr&oacute;xima: @if($evaluacion->proxima_evaluacion){{ $evaluacion->proxima_evaluacion->format('d/m/Y') }}@else sin programar @endif</small>@if($evaluacion->documento)<div>@include('iso.informes._documento',['documento'=>$evaluacion->documento])</div>@endif @if($evaluacion->enlace_externo)<div><a href="{{ $evaluacion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif</div>@empty<div class="text-muted">Sin evaluaciones.</div>@endforelse
        <div class="mt-2"><strong>Estado del cierre:</strong> @if($cierre)<span class="report-status ok">Evaluado {{ $cierre->fecha_evaluacion->format('d/m/Y') }}</span> &middot; {{ ucfirst(str_replace('_',' ',$cierre->decision)) }}@else<span class="report-status warn">Pendiente de evaluaci&oacute;n de cierre</span>@endif</div>
        @if($objetivo->origenContinuidad || $objetivo->continuidades->isNotEmpty())<div class="mt-2"><strong>Continuidad:</strong> @if($objetivo->origenContinuidad)<a href="{{ route('planificacion.objetivos.show',$objetivo->origenContinuidad) }}">proviene de {{ $objetivo->origenContinuidad->codigo }} ({{ $objetivo->origenContinuidad->periodo?->anio }})</a>@endif @foreach($objetivo->continuidades as $continuidad) &middot; <a href="{{ route('planificacion.objetivos.show',$continuidad) }}">contin&uacute;a como {{ $continuidad->codigo }} ({{ $continuidad->periodo?->anio }})</a>@endforeach</div>@endif
        @if($objetivo->contextos->isNotEmpty() || $objetivo->riesgos->isNotEmpty() || $objetivo->partes->isNotEmpty())<div class="mt-2"><strong>Relaciones:</strong> @foreach($objetivo->contextos as $item)<a href="{{ route('planificacion.foda.show',$item) }}">{{ $item->codigo }}</a> @endforeach @foreach($objetivo->riesgos as $item)<a href="{{ route('planificacion.riesgos.show',$item) }}">{{ $item->codigo }}</a> @endforeach @foreach($objetivo->partes as $item){{ $item->nombre }}@unless($loop->last), @endunless @endforeach</div>@endif
        @if($objetivo->revisiones->isNotEmpty())<div class="mt-2"><strong>Cambios de planificaci&oacute;n</strong>@foreach($objetivo->revisiones as $revision)<div><small>{{ $revision->fecha_vigencia->format('d/m/Y') }} &middot; {{ $revision->tipo==='correccion'?'Correcci&oacute;n':'Revisi&oacute;n' }} &middot; {{ $revision->motivo }} &middot; {{ $revision->realizadaPor?->name ?? 'Usuario no disponible' }}</small></div>@endforeach</div>@endif
    </div>
@empty<div class="text-muted">Sin objetivos de calidad.</div>@endforelse
</div></div>
