@extends('layouts.main')
@include('iso._styles')
@section('heading','Informe de planificación')
@section('contenidoPrincipal')
<div class="iso-shell">@include('iso._alerts')<div class="iso-toolbar no-print"><form method="GET"><select name="periodo" class="form-control" onchange="this.form.submit()">@foreach($periodos as $p)<option value="{{ $p->id }}" @selected($periodo->id===$p->id)>{{ $p->anio }}</option>@endforeach</select></form><button class="btn btn-primary" onclick="window.print()"><i class="fa-solid fa-print mr-1"></i> Imprimir / guardar PDF</button></div>
<div class="iso-eyebrow">Informe para auditoría</div><h1 class="iso-title">Contexto, riesgos y oportunidades — {{ $periodo->anio }}</h1><p class="iso-subtitle">Generado {{ now()->format('d/m/Y H:i') }} · Estado del período: {{ ucfirst($periodo->estado) }}</p>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Cambio climático</h2></div><div class="iso-panel-body"><strong>Relevante para el SGC:</strong> {{ is_null($periodo->cambio_climatico_relevante)?'Pendiente':($periodo->cambio_climatico_relevante?'Sí':'No') }}<p class="mb-0 mt-2">{{ $periodo->fundamento_cambio_climatico }}</p></div></div>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Contexto FODA</h2></div><div class="table-responsive"><table class="table iso-table mb-0"><thead><tr><th>Código</th><th>Tipo</th><th>Elemento</th><th>Relevante</th><th>Decisión</th><th>Justificación</th></tr></thead><tbody>@foreach($periodo->contextos as $c)<tr><td>{{ $c->codigo }}</td><td>{{ ucfirst($c->tipo) }}</td><td><strong>{{ $c->titulo }}</strong><div>{{ $c->descripcion }}</div></td><td>{{ is_null($c->relevante_sgc)?'Pendiente':($c->relevante_sgc?'Sí':'No') }}</td><td>{{ ucfirst(str_replace('_',' ',$c->decision)) }}</td><td>{{ $c->justificacion }}</td></tr>@endforeach</tbody></table></div></div>
<div class="iso-panel mb-4"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Riesgos, oportunidades y acciones</h2></div><div class="table-responsive"><table class="table iso-table mb-0"><thead><tr><th>Código</th><th>Tipo</th><th>Identificación / efecto</th><th>Índice inicial</th><th>Acciones y evidencias</th><th>Eficacia / residual</th></tr></thead><tbody>@foreach($periodo->riesgos as $r)<tr><td>{{ $r->codigo }}</td><td>{{ ucfirst($r->tipo) }}</td><td>{{ $r->identificacion }}<div class="text-muted">{{ $r->efecto_potencial }}</div></td><td>{{ $r->indice_inicial }}</td><td>@foreach($r->acciones as $a)<strong>{{ $a->descripcion }}</strong> — {{ ucfirst(str_replace('_',' ',$a->estado)) }}@foreach($a->seguimientos as $s)<div><small>{{ $s->fecha->format('d/m/Y') }}: {{ $s->detalle }} @if($s->documento)· Doc. SGD: {{ $s->documento->titulo }}@endif</small></div>@endforeach @endforeach</td><td>{{ ucfirst($r->eficacia) }}@if($r->indice_final)<div>Índice final: {{ $r->indice_final }}</div>@endif<div>{{ $r->conclusion_eficacia }}</div></td></tr>@endforeach</tbody></table></div></div>
<div class="iso-panel"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Partes interesadas y evaluación periódica</h2></div><div class="table-responsive"><table class="table iso-table mb-0"><thead><tr><th>Parte</th><th>Necesidades / requisitos</th><th>Área responsable</th><th>Método de medición</th><th>Evaluación aplicable</th><th>Evidencia / vínculos</th></tr></thead><tbody>@foreach($partes as $parte)@php($evaluacion=$parte->evaluaciones->firstWhere('periodo_id',$periodo->id) ?? $parte->evaluaciones->first())<tr><td><strong>{{ $parte->nombre }}</strong><div>{{ $parte->pertinente_sgc?'Pertinente':'No pertinente' }}</div>@if(!is_null($parte->requisitos_climaticos))<small>Req. climáticos: {{ $parte->requisitos_climaticos?'Sí':'No identificados' }}</small>@endif</td><td>{{ $parte->necesidades_requisitos }}</td><td>{{ $parte->area_responsable ?: 'Pendiente de definir' }}</td><td>{{ $parte->metodo_medicion }}</td><td>@if($evaluacion)<strong>{{ $evaluacion->fecha_evaluacion->format('d/m/Y') }} — {{ ucfirst(str_replace('_',' ',$evaluacion->resultado)) }}</strong>@if($evaluacion->periodo_id!==$periodo->id)<div class="text-muted">Última evaluación disponible; no pertenece al período {{ $periodo->anio }}.</div>@endif<div>{{ $evaluacion->observaciones }}</div>@else<span class="text-muted">Sin evaluaciones registradas</span>@endif</td><td>@if($evaluacion?->documento)@if($documentosAccesibles->contains($evaluacion->documento_id))<a href="{{ route('documentos.validaPermiso',['id'=>$evaluacion->documento->id,'ruta'=>'documentos.show','permiso'=>'puedeLeer']) }}">Doc. SGD: {{ $evaluacion->documento->titulo }}</a>@else<span class="text-muted">Documento interno vinculado — sin permiso de acceso</span>@endif<br>@endif @if($evaluacion?->enlace_externo)<a href="{{ $evaluacion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a><br>@endif @foreach($evaluacion?->riesgos ?? [] as $riesgo)<a href="{{ route('planificacion.riesgos.show',$riesgo) }}">{{ $riesgo->codigo }}</a> @endforeach</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
