@extends('layouts.main')
@include('iso._styles')
@section('heading',$objetivo->codigo)
@section('contenidoPrincipal')
@php
    $puedeGestionar = auth()->user()->puedeGestionarPlanificacion();
    $cumplimientoTexto = match($cumplimiento){'cumplido'=>'Cumplido','aceptable'=>'Aceptable','incumplido'=>'Incumplido',default=>'Pendiente de medición'};
    $cumplimientoClase = match($cumplimiento){'cumplido'=>'ok','aceptable'=>'warn','incumplido'=>'danger',default=>''};
    $simbolo = match($indicador?->comparador){'mayor_igual'=>'≥','mayor'=>'>','menor_igual'=>'≤','menor'=>'<','igual'=>'=','rango'=>'entre',default=>''};
    $fmt = fn($valor) => $valor === null ? 'Sin datos' : rtrim(rtrim(number_format((float)$valor,4,',','.'),'0'),',');
@endphp
<div class="iso-shell iso-objective-view">
    @include('iso._alerts')
    <a href="{{ route('planificacion.objetivos.index',['periodo'=>$objetivo->periodo_id]) }}" class="text-decoration-none">← Volver a objetivos de calidad</a>
    <div class="d-flex justify-content-between align-items-start gap-3 mt-3 flex-wrap">
        <div><span class="iso-code">{{ $objetivo->codigo }}</span><h1 class="iso-title">{{ $objetivo->titulo }}</h1><p class="iso-subtitle">{{ $objetivo->descripcion ?: 'Sin descripción adicional.' }}</p></div>
        <div class="text-end"><span class="iso-status {{ $cumplimientoClase }}">{{ $cumplimientoTexto }}</span><div class="mt-2">{{ ucfirst($objetivo->estado) }}</div>@if($puedeGestionar && $objetivo->estado==='activo' && $objetivo->periodo->estado!=='cerrado')<button type="button" class="btn btn-outline-primary btn-sm mt-3" id="gestionarObjetivo"><i class="fa-regular fa-pen-to-square mr-1"></i> {{ $tieneActividad ? 'Revisar planificación' : 'Corregir objetivo' }}</button>@endif</div>
    </div>

    <div class="iso-panel mt-4">
        <div class="iso-panel-body">
            <div class="iso-detail-grid">
                <div class="iso-field"><label>Compromiso de la política</label><div>{{ $objetivo->compromiso_politica }}</div></div>
                <div class="iso-field"><label>Proceso</label><div>{{ $objetivo->proceso }}</div></div>
                <div class="iso-field"><label>Responsabilidad</label><div>{{ $objetivo->area_responsable }} · {{ $objetivo->responsable?->name ?? 'Sin asignar' }}</div></div>
                <div class="iso-field"><label>Planificación</label><div>{{ $objetivo->fecha_inicio->format('d/m/Y') }} al {{ $objetivo->fecha_objetivo->format('d/m/Y') }} · Seguimiento {{ strtolower($objetivo->periodicidad_seguimiento) }}</div></div>
                <div class="iso-field"><label>Indicador</label><div>{{ $indicador?->nombre }}<small class="d-block text-muted mt-1">{{ $indicador?->metodo_calculo }}</small></div></div>
                <div class="iso-field"><label>Fuente y frecuencia</label><div>{{ $indicador?->fuente }} · {{ $indicador?->frecuencia }}</div></div>
                <div class="iso-field"><label>Meta</label><div>{{ $simbolo }} {{ $fmt($indicador?->meta) }}@if($indicador?->comparador==='rango') y {{ $fmt($indicador?->meta_hasta) }}@endif {{ $indicador?->unidad }}@if($indicador?->tolerancia !== null)<small class="d-block text-muted">Tolerancia aceptable: {{ $fmt($indicador->tolerancia) }}</small>@endif</div></div>
                <div class="iso-field"><label>Resultado actual</label><div><strong class="fs-5">{{ $fmt($resultado) }}</strong> {{ $resultado !== null ? $indicador?->unidad : '' }}<small class="d-block text-muted">Cálculo: {{ match($indicador?->agregacion){'promedio'=>'promedio de mediciones','suma'=>'suma acumulada','variacion'=>'variación absoluta','variacion_porcentual'=>'variación porcentual',default=>'última medición'} }}</small></div></div>
            </div>
        </div>
    </div>

    <ul class="nav nav-tabs iso-tabs mt-4" role="tablist">
        <li class="nav-item"><a class="nav-link active" id="mediciones-tab" data-toggle="tab" href="#mediciones" role="tab" aria-controls="mediciones" aria-selected="true"><i class="fa-solid fa-chart-line mr-1"></i> Mediciones <span class="ml-1">{{ $indicador?->mediciones->count() ?? 0 }}</span></a></li>
        <li class="nav-item"><a class="nav-link" id="acciones-tab" data-toggle="tab" href="#acciones" role="tab" aria-controls="acciones" aria-selected="false"><i class="fa-solid fa-list-check mr-1"></i> Acciones y evidencias <span class="ml-1">{{ $objetivo->acciones->count() }}</span></a></li>
        <li class="nav-item"><a class="nav-link" id="evaluaciones-tab" data-toggle="tab" href="#evaluaciones" role="tab" aria-controls="evaluaciones" aria-selected="false"><i class="fa-solid fa-clipboard-check mr-1"></i> Evaluaciones <span class="ml-1">{{ $objetivo->evaluaciones->count() }}</span></a></li>
        <li class="nav-item"><a class="nav-link" id="ficha-tab" data-toggle="tab" href="#ficha" role="tab" aria-controls="ficha" aria-selected="false"><i class="fa-solid fa-link mr-1"></i> Ficha y relaciones</a></li>
    </ul>

    <div class="tab-content pt-3">
        <div class="tab-pane fade show active" id="mediciones">
            <div class="iso-panel iso-section-card mb-3">
                <div class="iso-panel-header"><div><h2 class="iso-section-title mb-1">Historial de mediciones</h2><small class="text-muted">Cada resultado conserva fecha, fuente, observación y evidencia.</small></div></div>
                <div class="iso-panel-body">
                    @if($indicador?->mediciones->isNotEmpty())
                    <div class="table-responsive"><table class="table iso-table"><thead><tr><th>Fecha</th><th>Referencia</th><th>Valor</th><th>Observación</th><th>Evidencia</th></tr></thead><tbody>
                        @foreach($indicador->mediciones->sortByDesc('fecha_medicion') as $medicion)<tr><td>{{ $medicion->fecha_medicion->format('d/m/Y') }}</td><td>{{ $medicion->periodo_referencia ?: '—' }}</td><td><strong>{{ $fmt($medicion->valor) }}</strong> {{ $indicador->unidad }}</td><td>{{ $medicion->observaciones ?: '—' }}</td><td>@if($medicion->documento)<a href="{{ route('documentos.validaPermiso',['id'=>$medicion->documento->id,'ruta'=>'documentos.show','permiso'=>'puedeLeer']) }}">Doc. SGD: {{ $medicion->documento->titulo }}</a>@elseif($medicion->enlace_externo)<a href="{{ $medicion->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a>@else—@endif</td></tr>@endforeach
                    </tbody></table></div>
                    @else<div class="iso-empty-card"><i class="fa-solid fa-chart-line me-3"></i><div><strong>Sin mediciones registradas</strong><small>El cumplimiento permanecerá pendiente hasta registrar el primer valor.</small></div></div>@endif
                </div>
            </div>
            @if($puedeGestionar && $objetivo->estado==='activo' && $objetivo->periodo->estado!=='cerrado')
            <div class="iso-panel">
                <div class="iso-panel-header"><h2 class="iso-section-title mb-0">Registrar medición</h2></div>
                <form method="post" action="{{ route('planificacion.objetivos.mediciones.store',[$objetivo,$indicador]) }}" class="iso-panel-body">@csrf
                    <div class="row g-3"><div class="col-md-3"><label class="form-label">Fecha *</label><input type="date" name="fecha_medicion" value="{{ date('Y-m-d') }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Período de referencia</label><input name="periodo_referencia" class="form-control" placeholder="Ej.: Julio 2026"></div><div class="col-md-3"><label class="form-label">Valor *</label><input type="number" step="any" name="valor" class="form-control" required></div><div class="col-md-3"><label class="form-label">Documento del SGD</label><select name="documento_id" class="form-select"><option value="">Sin documento</option>@foreach($documentos as $documento)<option value="{{ $documento->id }}">{{ $documento->titulo }}</option>@endforeach</select></div><div class="col-md-8"><label class="form-label">Observaciones</label><input name="observaciones" class="form-control"></div><div class="col-md-4"><label class="form-label">Evidencia externa</label><input type="url" name="enlace_externo" class="form-control" placeholder="https://..."></div></div>
                    <button class="btn btn-primary mt-3">Registrar medición</button>
                </form>
            </div>@endif
        </div>

        <div class="tab-pane fade" id="acciones">
            <div class="iso-panel iso-section-card mb-3"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Acciones y evidencias</h2><span class="iso-status">{{ $objetivo->acciones->whereIn('estado',['completada','cancelada'])->count() }}/{{ $objetivo->acciones->count() }} resueltas</span></div><div class="iso-panel-body">
                @forelse($objetivo->acciones as $accion)
                @php $cerrada=in_array($accion->estado,['completada','cancelada']); @endphp
                <div class="iso-action-card"><button class="iso-action-summary" type="button" data-toggle="collapse" data-target="#accion{{ $accion->id }}" aria-expanded="false" aria-controls="accion{{ $accion->id }}"><span><strong>{{ $accion->descripcion }}</strong><small>{{ $accion->area_responsable }} · {{ $accion->responsable?->name ?? 'Sin asignar' }} · Objetivo {{ $accion->fecha_objetivo->format('d/m/Y') }}</small></span><span><span class="iso-status {{ $accion->estado==='completada'?'ok':($accion->estado==='cancelada'?'danger':'') }}">{{ ucfirst(str_replace('_',' ',$accion->estado)) }}</span> <i class="fa-solid fa-chevron-down iso-action-chevron ml-2"></i></span></button>
                    <div class="collapse iso-action-detail" id="accion{{ $accion->id }}">
                        @if($accion->resultado)<p><strong>Resultado:</strong> {{ $accion->resultado }}</p>@endif
                        @foreach($accion->seguimientos->sortByDesc('fecha') as $seguimiento)<div class="border-start ps-3 py-1 mb-2"><strong>{{ $seguimiento->fecha->format('d/m/Y') }}</strong> — {{ $seguimiento->detalle }}@if($seguimiento->documento)<div><a href="{{ route('documentos.validaPermiso',['id'=>$seguimiento->documento->id,'ruta'=>'documentos.show','permiso'=>'puedeLeer']) }}">Doc. SGD: {{ $seguimiento->documento->titulo }}</a></div>@elseif($seguimiento->enlace_externo)<div><a href="{{ $seguimiento->enlace_externo }}" target="_blank">Evidencia externa</a></div>@endif</div>@endforeach
                        @if($puedeGestionar && $objetivo->estado==='activo' && $objetivo->periodo->estado!=='cerrado')
                        <form method="post" action="{{ route('planificacion.objetivos.acciones.seguimientos.store',$accion) }}" class="row g-2 mt-3">@csrf<div class="col-md-2"><input type="date" name="fecha" value="{{ date('Y-m-d') }}" class="form-control" required></div><div class="col-md-4"><input name="detalle" class="form-control" placeholder="Seguimiento o evidencia" required></div><div class="col-md-3"><select name="documento_id" class="form-select"><option value="">Sin documento</option>@foreach($documentos as $documento)<option value="{{ $documento->id }}">{{ $documento->titulo }}</option>@endforeach</select></div><div class="col-md-2"><input type="url" name="enlace_externo" class="form-control" placeholder="https://..."></div><div class="col-md-1"><button class="btn btn-outline-primary">Agregar</button></div></form>
                        @if(!$cerrada)<form method="post" action="{{ route('planificacion.objetivos.acciones.update',$accion) }}" class="row g-2 mt-3">@csrf @method('patch')<div class="col-md-3"><select name="estado" class="form-select"><option value="pendiente" @selected($accion->estado==='pendiente')>Pendiente</option><option value="en_proceso" @selected($accion->estado==='en_proceso')>En proceso</option><option value="completada">Completada</option><option value="cancelada">Cancelada</option></select></div><div class="col-md-6"><input name="resultado" class="form-control" placeholder="Resultado obtenido o motivo de cancelación"></div><div class="col-md-3"><button class="btn btn-primary">Guardar estado</button></div></form>
                        @else<form method="post" action="{{ route('planificacion.objetivos.acciones.reabrir',$accion) }}" class="mt-3 border-top pt-3">@csrf @method('patch')<div class="row g-2"><div class="col-md-6"><input name="motivo" class="form-control" placeholder="Justificación de la reapertura" required></div><div class="col-md-3"><input name="confirmacion" class="form-control" placeholder="Escribí REABRIR ACCION" required></div><div class="col-md-3 d-flex align-items-center gap-2"><input type="checkbox" name="comprende_impacto" value="1" required> <small>Comprendo el impacto</small><button class="btn btn-outline-warning ms-auto">Reabrir</button></div></div></form>@endif
                        @endif
                    </div>
                </div>
                @empty<div class="iso-empty-card"><i class="fa-solid fa-list-check me-3"></i><div><strong>Sin acciones</strong><small>El objetivo puede medirse sin acciones o incorporarlas cuando se detecte una necesidad.</small></div></div>@endforelse
            </div></div>
            @if($puedeGestionar && $objetivo->estado==='activo' && $objetivo->periodo->estado!=='cerrado')<div class="iso-panel"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Agregar acción</h2></div><form method="post" action="{{ route('planificacion.objetivos.acciones.store',$objetivo) }}" class="iso-panel-body">@csrf<div class="row g-3"><div class="col-12"><label class="form-label">Descripción *</label><textarea name="descripcion" class="form-control" rows="2" required></textarea></div><div class="col-md-4"><label class="form-label">Área responsable *</label><select name="area_responsable" class="form-select" required>@foreach($areas as $area)<option>{{ $area }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Responsable</label><select name="responsable_id" class="form-select"><option value="">Sin asignar</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}">{{ $usuario->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Fecha objetivo *</label><input type="date" name="fecha_objetivo" class="form-control" required></div></div><button class="btn btn-primary mt-3">Agregar acción</button></form></div>@endif
        </div>

        <div class="tab-pane fade" id="evaluaciones">
            <div class="iso-panel iso-section-card mb-3"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Historial de evaluaciones</h2>@if($puedeGestionar && $objetivo->estado==='activo' && $resultado!==null)<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#evaluarObjetivo" aria-expanded="false" aria-controls="evaluarObjetivo"><i class="fa-solid fa-clipboard-check mr-1"></i> Evaluar objetivo</button>@endif</div><div class="iso-panel-body">
                @forelse($objetivo->evaluaciones as $evaluacion)<div class="iso-evaluation-card {{ $evaluacion->cumplimiento==='cumplido'?'is-effective':($evaluacion->cumplimiento==='aceptable'?'is-partial':'is-ineffective') }}"><div class="d-flex justify-content-between gap-3"><div><strong>{{ $evaluacion->fecha_evaluacion->format('d/m/Y') }} — {{ ucfirst($evaluacion->cumplimiento) }}</strong><small class="d-block text-muted">{{ $evaluacion->evaluadoPor?->name ?? 'Sin identificar' }} · Resultado {{ $fmt($evaluacion->resultado) }}</small></div><span class="iso-status">{{ ucfirst($evaluacion->decision) }}</span></div><p class="mt-3 mb-1">{{ $evaluacion->conclusion }}</p>@if($evaluacion->justificacion)<div class="iso-decision-reason mt-2"><label>Justificación</label><div>{{ $evaluacion->justificacion }}</div></div>@endif</div>@empty<div class="iso-empty-card"><i class="fa-solid fa-clipboard-check me-3"></i><div><strong>Sin evaluaciones</strong><small>Registrá mediciones y luego evaluá si la meta fue alcanzada.</small></div></div>@endforelse
            </div></div>
            @if($puedeGestionar && $objetivo->estado==='activo' && $resultado!==null && $objetivo->periodo->estado!=='cerrado')<div class="collapse" id="evaluarObjetivo"><div class="iso-panel iso-section-card"><div class="iso-panel-header"><div><h2 class="iso-section-title mb-1">Nueva evaluación</h2><small>Resultado automático: {{ $cumplimientoTexto }} con {{ $fmt($resultado) }} {{ $indicador->unidad }}</small></div></div><form method="post" action="{{ route('planificacion.objetivos.evaluaciones.store',$objetivo) }}" class="iso-panel-body" id="formEvaluacion">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Fecha *</label><input type="date" name="fecha_evaluacion" value="{{ date('Y-m-d') }}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Cumplimiento *</label><select name="cumplimiento" id="cumplimientoEvaluacion" data-calculado="{{ $cumplimiento }}" class="form-select" required><option value="cumplido" @selected($cumplimiento==='cumplido')>Cumplido</option><option value="aceptable" @selected($cumplimiento==='aceptable')>Aceptable con justificación</option><option value="incumplido" @selected($cumplimiento==='incumplido')>Incumplido</option></select></div><div class="col-md-5"><label class="form-label">Decisión posterior *</label><select name="decision" id="decisionEvaluacion" class="form-select" required><option value="continuar">Continuar seguimiento</option><option value="reformular">Reformular objetivo o meta</option><option value="cerrar">Cerrar objetivo</option><option value="suspender">Suspender objetivo</option></select></div><div class="col-12"><label class="form-label">Conclusión *</label><textarea name="conclusion" class="form-control" rows="3" required></textarea></div><div class="col-12 d-none" id="justificacionEvaluacion"><label class="form-label">Justificación *</label><textarea name="justificacion" class="form-control" rows="2"></textarea><small class="text-muted">Obligatoria para un resultado aceptable o una excepción respecto del cálculo automático.</small></div><div class="col-md-4" id="proximaEvaluacion"><label class="form-label">Próxima evaluación *</label><input type="date" name="proxima_evaluacion" class="form-control"></div><div class="col-md-4"><label class="form-label">Documento del SGD</label><select name="documento_id" class="form-select"><option value="">Sin documento</option>@foreach($documentos as $documento)<option value="{{ $documento->id }}">{{ $documento->titulo }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Evidencia externa</label><input type="url" name="enlace_externo" class="form-control" placeholder="https://..."></div></div><button class="btn btn-primary mt-3">Registrar evaluación</button></form></div></div>@endif
        </div>

        <div class="tab-pane fade" id="ficha">
            <div class="iso-panel mb-3"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Relaciones de planificación</h2></div><div class="iso-panel-body"><div class="row g-4"><div class="col-md-4"><strong>FODA</strong>@forelse($objetivo->contextos as $item)<a class="d-block mt-2" href="{{ route('planificacion.foda.show',$item) }}">{{ $item->codigo }} — {{ $item->titulo }}</a>@empty<p class="text-muted mt-2">Sin relación</p>@endforelse</div><div class="col-md-4"><strong>Riesgos y oportunidades</strong>@forelse($objetivo->riesgos as $item)<a class="d-block mt-2" href="{{ route('planificacion.riesgos.show',$item) }}">{{ $item->codigo }} — {{ $item->identificacion }}</a>@empty<p class="text-muted mt-2">Sin relación</p>@endforelse</div><div class="col-md-4"><strong>Partes interesadas</strong>@forelse($objetivo->partes as $item)<a class="d-block mt-2" href="{{ route('planificacion.partes.show',$item) }}">{{ $item->nombre }}</a>@empty<p class="text-muted mt-2">Sin relación</p>@endforelse</div></div></div></div>
            @if($puedeGestionar && $objetivo->estado==='activo' && $objetivo->periodo->estado!=='cerrado')<div class="iso-panel"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Editar definición e indicador</h2></div><form method="post" action="{{ route('planificacion.objetivos.update',$objetivo) }}" class="iso-panel-body">@csrf @method('patch')<input type="hidden" name="periodo_id" value="{{ $objetivo->periodo_id }}"><div class="row g-3"><div class="col-md-6"><label class="form-label">Objetivo *</label><input name="titulo" value="{{ $objetivo->titulo }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Proceso *</label><input name="proceso" value="{{ $objetivo->proceso }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Área *</label><input name="area_responsable" value="{{ $objetivo->area_responsable }}" class="form-control" required></div><div class="col-12"><label class="form-label">Compromiso de la política *</label><textarea name="compromiso_politica" class="form-control" rows="2" required>{{ $objetivo->compromiso_politica }}</textarea></div><div class="col-12"><label class="form-label">Descripción</label><textarea name="descripcion" class="form-control" rows="2">{{ $objetivo->descripcion }}</textarea></div><div class="col-md-3"><label class="form-label">Responsable</label><select name="responsable_id" class="form-select"><option value="">Sin asignar</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}" @selected($objetivo->responsable_id===$usuario->id)>{{ $usuario->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Inicio *</label><input type="date" name="fecha_inicio" value="{{ $objetivo->fecha_inicio->format('Y-m-d') }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Fecha objetivo *</label><input type="date" name="fecha_objetivo" value="{{ $objetivo->fecha_objetivo->format('Y-m-d') }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Seguimiento *</label><input name="periodicidad_seguimiento" value="{{ $objetivo->periodicidad_seguimiento }}" class="form-control" required></div><div class="col-12"><label class="form-label">Observaciones</label><input name="observaciones" value="{{ $objetivo->observaciones }}" class="form-control"></div>
                    <div class="col-12"><hr><h3 class="iso-section-title">Indicador principal</h3></div><div class="col-md-6"><label class="form-label">Nombre *</label><input name="indicador_nombre" value="{{ $indicador->nombre }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Fuente *</label><input name="indicador_fuente" value="{{ $indicador->fuente }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Unidad *</label><input name="indicador_unidad" value="{{ $indicador->unidad }}" class="form-control" required></div><div class="col-12"><label class="form-label">Método de cálculo *</label><textarea name="indicador_metodo_calculo" class="form-control" required>{{ $indicador->metodo_calculo }}</textarea></div><div class="col-md-3"><label class="form-label">Frecuencia *</label><input name="indicador_frecuencia" value="{{ $indicador->frecuencia }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Agregación *</label><select name="indicador_agregacion" class="form-select">@foreach(['ultimo'=>'Último','promedio'=>'Promedio','suma'=>'Suma','variacion'=>'Variación absoluta','variacion_porcentual'=>'Variación porcentual'] as $valor=>$texto)<option value="{{ $valor }}" @selected($indicador->agregacion===$valor)>{{ $texto }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Comparador *</label><select name="indicador_comparador" class="form-select">@foreach(['mayor_igual'=>'Mayor o igual','mayor'=>'Mayor','menor_igual'=>'Menor o igual','menor'=>'Menor','igual'=>'Igual','rango'=>'Rango'] as $valor=>$texto)<option value="{{ $valor }}" @selected($indicador->comparador===$valor)>{{ $texto }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Meta *</label><input type="number" step="any" name="indicador_meta" value="{{ $indicador->meta }}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Meta hasta</label><input type="number" step="any" name="indicador_meta_hasta" value="{{ $indicador->meta_hasta }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Tolerancia</label><input type="number" min="0" step="any" name="indicador_tolerancia" value="{{ $indicador->tolerancia }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Línea base</label><input type="number" step="any" name="indicador_linea_base" value="{{ $indicador->linea_base }}" class="form-control"></div>
                    <div class="col-md-4"><label class="form-label">FODA</label><select name="contextos[]" class="form-select" multiple size="4">@foreach($contextos as $item)<option value="{{ $item->id }}" @selected($objetivo->contextos->contains($item))>{{ $item->codigo }} — {{ $item->titulo }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Riesgos y oportunidades</label><select name="riesgos[]" class="form-select" multiple size="4">@foreach($riesgos as $item)<option value="{{ $item->id }}" @selected($objetivo->riesgos->contains($item))>{{ $item->codigo }} — {{ $item->identificacion }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Partes interesadas</label><select name="partes[]" class="form-select" multiple size="4">@foreach($partes as $item)<option value="{{ $item->id }}" @selected($objetivo->partes->contains($item))>{{ $item->nombre }}</option>@endforeach</select></div></div><button class="btn btn-primary mt-3">Guardar cambios</button></form></div>@endif
        </div>
    </div>

    <div class="iso-panel mt-4">
        <div class="iso-panel-header"><div><h2 class="iso-section-title mb-1">Historial de correcciones y revisiones</h2><small class="text-muted">Conserva quién modificó la planificación, cuándo comenzó a regir y por qué.</small></div></div>
        <div class="iso-panel-body">
            @forelse($objetivo->revisiones as $revision)
                <div class="iso-evaluation-card mb-3">
                    <div class="d-flex justify-content-between align-items-start gap-3"><div><strong>{{ $revision->fecha_vigencia->format('d/m/Y') }} — {{ $revision->tipo === 'correccion' ? 'Corrección administrativa' : 'Revisión de planificación' }}</strong><small class="d-block text-muted">{{ $revision->realizadaPor?->name ?? 'Usuario no disponible' }} · Registrada {{ $revision->created_at->format('d/m/Y H:i') }}</small></div><span class="iso-status">{{ $revision->tipo === 'correccion' ? 'Corrección' : 'Revisión' }}</span></div>
                    <p class="mb-0 mt-2"><strong>Motivo:</strong> {{ $revision->motivo }}</p>
                </div>
            @empty
                <div class="iso-empty-card"><i class="fa-solid fa-clock-rotate-left mr-3"></i><div><strong>Sin cambios registrados</strong><small>La definición actual es la registrada originalmente.</small></div></div>
            @endforelse
        </div>
    </div>

    @if($puedeGestionar && !$tieneActividad && $objetivo->periodo->estado!=='cerrado')
    <div class="iso-panel mt-4 border-danger">
        <div class="iso-panel-header"><div><h2 class="iso-section-title mb-1">Eliminar objetivo creado por error</h2><small class="text-muted">Disponible porque no existen mediciones, evaluaciones ni acciones iniciadas.</small></div><button type="button" class="btn btn-outline-danger" data-toggle="collapse" data-target="#eliminarObjetivo">Eliminar</button></div>
        <form id="eliminarObjetivo" class="collapse iso-panel-body" method="post" action="{{ route('planificacion.objetivos.destroy',$objetivo) }}">@csrf @method('delete')
            <div class="alert alert-danger"><strong>Eliminación definitiva.</strong> Se eliminará la ficha y cualquier acción todavía pendiente. La operación quedará registrada en el historial de auditoría.</div>
            <div class="row g-3"><div class="col-md-6"><label class="form-label">Motivo de la eliminación *</label><textarea name="motivo_eliminacion" class="form-control" rows="2" required></textarea></div><div class="col-md-3"><label class="form-label">Confirmación *</label><input name="confirmacion_eliminacion" class="form-control" placeholder="ELIMINAR OBJETIVO" required></div><div class="col-md-3 d-flex align-items-end"><label class="mb-2"><input type="checkbox" name="comprende_eliminacion" value="1" required> Comprendo que no puede deshacerse</label></div></div>
            <button class="btn btn-danger mt-3">Eliminar definitivamente</button>
        </form>
    </div>
    @endif
</div>
@endsection
@push('styles')
<style>
.iso-objective-view .form-select{display:block;width:100%;min-height:38px;padding:.375rem .75rem;border:1px solid #ced4da;border-radius:.25rem;background:#fff;color:#212529}.iso-objective-view select[multiple].form-select{height:auto;min-height:110px}.iso-objective-view .form-label{font-weight:600;color:#344054}.iso-change-control{background:#f8fafc;border:1px solid #dbe4ef;border-radius:12px}
</style>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
 const planningForm=document.querySelector('form[action="{{ route('planificacion.objetivos.update',$objetivo) }}"]');
 if(planningForm){
   const hasActivity={{ $tieneActividad ? 'true' : 'false' }};
   if(hasActivity) planningForm.action="{{ route('planificacion.objetivos.revisar',$objetivo) }}";
   const heading=planningForm.closest('.iso-panel').querySelector('.iso-panel-header h2');
   heading.textContent=hasActivity?'Revisar planificación':'Corregir ficha creada recientemente';
   const submit=planningForm.querySelector('button[type="submit"], button:not([type])');
   const control=document.createElement('div');
   control.className='iso-change-control mt-4 p-3';
   control.innerHTML=`<div class="alert ${hasActivity?'alert-warning':'alert-info'} mb-3"><strong>${hasActivity?'Revisión controlada':'Corrección administrativa'}.</strong> ${hasActivity?'El objetivo ya tiene actividad. El cambio no alterará las evaluaciones históricas y conservará los valores anteriores.':'Podés corregir errores de carga porque todavía no existen mediciones, evaluaciones ni acciones iniciadas.'}</div><div class="row g-3">${hasActivity?'<div class="col-md-3"><label class="form-label">Vigente desde *</label><input type="date" name="fecha_vigencia" value="{{ date('Y-m-d') }}" max="{{ date('Y-m-d') }}" class="form-control" required></div>':''}<div class="${hasActivity?'col-md-6':'col-md-9'}"><label class="form-label">Motivo del cambio *</label><textarea name="motivo_cambio" class="form-control" rows="2" required placeholder="${hasActivity?'Explicá la decisión y su fundamento':'Indicá qué error de carga se corrige'}"></textarea></div><div class="col-md-3 d-flex align-items-end"><label class="mb-2"><input type="checkbox" name="confirmacion_cambio" value="1" required> ${hasActivity?'Comprendo el impacto de revisar la planificación':'Confirmo que es una corrección de carga'}</label></div></div>`;
   submit.parentNode.insertBefore(control,submit);
   submit.textContent=hasActivity?'Registrar revisión':'Guardar corrección';
 }
 const manageButton=document.getElementById('gestionarObjetivo');
 if(manageButton&&planningForm){
   manageButton.addEventListener('click',function(){
     const fichaTab=document.getElementById('ficha-tab');
     if(fichaTab) fichaTab.click();
     planningForm.scrollIntoView({behavior:'smooth',block:'start'});
   });
 }
 const result=document.getElementById('cumplimientoEvaluacion'), decision=document.getElementById('decisionEvaluacion');
 if(!result||!decision)return; const justification=document.getElementById('justificacionEvaluacion'), next=document.getElementById('proximaEvaluacion');
 function sync(){const needs=result.value==='aceptable'||result.value!==result.dataset.calculado;justification.classList.toggle('d-none',!needs);justification.querySelector('textarea').required=needs;const continues=['continuar','reformular'].includes(decision.value);next.classList.toggle('d-none',!continues);next.querySelector('input').required=continues;}
 result.addEventListener('change',sync);decision.addEventListener('change',sync);sync();
});
</script>
@endpush
