<?php

return [
    'compromisos_politica' => [
        'Cumplimiento de requisitos de clientes y partes interesadas',
        'Satisfacción del cliente',
        'Compromiso con las personas',
        'Disposición al cambio e innovación',
        'Mejora continua',
        'Calidad de productos y servicios',
    ],
    'frecuencias' => ['Mensual', 'Bimestral', 'Trimestral', 'Cuatrimestral', 'Semestral', 'Anual', 'Por proyecto', 'Única vez'],
    'unidades_indicador' => ['Porcentaje', 'Cantidad', 'Días', 'Horas', 'Importe', 'Índice', 'Puntos', 'Otra'],
    'procesos' => [
        'Dirección y planificación estratégica',
        'Gestión comercial',
        'Desarrollo de productos y servicios',
        'Desarrollo de software',
        'Implementación de soluciones',
        'Soporte y atención al cliente',
        'Gestión de infraestructura',
        'Seguridad de la información',
        'Compras y proveedores',
        'Recursos humanos',
        'Administración y finanzas',
        'Gestión documental',
        'Gestión de la calidad',
    ],
    'partes_interesadas' => [
        'Clientes',
        'Usuarios finales',
        'Personal',
        'Dirección',
        'Proveedores y socios tecnológicos',
        'Organismos regulatorios',
        'Accionistas',
        'Comunidad',
    ],
    'areas_responsables' => [
        'Directorio',
        'RRHH',
        'Administración',
        'Comercial',
        'Desarrollo',
        'Infraestructura',
        'Soporte',
        'Calidad',
    ],
    'fuentes' => [
        'Seguimiento tecnológico',
        'Análisis de mercado',
        'Necesidad o consulta de clientes',
        'Indicadores y datos internos',
        'Auditoría',
        'Revisión por la dirección',
        'Cambio legal o reglamentario',
        'Proveedor o socio tecnológico',
        'Análisis interno',
        'Experiencia o lección aprendida',
    ],
    'referencias' => [
        'Documento del SGD',
        'Riesgo u oportunidad existente',
        'Elemento FODA anterior',
        'Tarjeta Kanbanize',
        'Proyecto o iniciativa interna',
        'Acta o minuta',
        'Enlace externo',
    ],
];
