@extends('layouts.main')
@include('iso._styles')
@section('heading','Nuevo riesgo u oportunidad')
@section('contenidoPrincipal')
<div class="iso-shell"><a href="{{ url()->previous() }}">← Volver</a><div class="iso-eyebrow mt-3">{{ $contexto?->codigo ?? 'Registro independiente' }}</div><h1 class="iso-title">Nuevo riesgo u oportunidad</h1>@include('iso._alerts')
<form method="POST" action="{{ route('planificacion.riesgos.store') }}" class="iso-panel"><div class="iso-panel-body">@csrf<input type="hidden" name="periodo_id" value="{{ $periodo->id }}"><input type="hidden" name="contexto_id" value="{{ $contexto?->id }}">
    @if($contexto)<div class="alert alert-info"><strong>Origen:</strong> {{ ucfirst($contexto->tipo) }} — {{ $contexto->titulo }}</div>@endif
    @php($procesoActual=old('proceso',$contexto?->proceso))
    <div class="form-row"><div class="form-group col-md-3"><label>Tipo *</label><select name="tipo" class="form-control" required><option value="riesgo" @selected(old('tipo',in_array($contexto?->tipo,['debilidad','amenaza'])?'riesgo':'oportunidad')==='riesgo')>Riesgo</option><option value="oportunidad" @selected(old('tipo',in_array($contexto?->tipo,['debilidad','amenaza'])?'riesgo':'oportunidad')==='oportunidad')>Oportunidad</option></select><small class="form-text text-muted">Las amenazas y debilidades suelen originar riesgos; las fortalezas y oportunidades pueden originar oportunidades.</small></div><div class="form-group col-md-5"><label>Proceso *</label><select name="proceso" class="form-control" required data-other-target="riesgoProcesoOtro"><option value="">Seleccionar proceso</option>@foreach($procesos as $proceso)<option value="{{ $proceso }}" @selected($procesoActual===$proceso)>{{ $proceso }}</option>@endforeach<option value="__otro__" @selected($procesoActual && !$procesos->contains($procesoActual))>Otro</option></select><div id="riesgoProcesoOtro" class="mt-2 d-none"><input name="proceso_otro" class="form-control" value="{{ $procesoActual && !$procesos->contains($procesoActual) ? $procesoActual : old('proceso_otro') }}" placeholder="Escribí el nombre del proceso"></div><small class="form-text text-muted">Elegí el proceso que podría sufrir el efecto o que gestionará la oportunidad.</small></div><div class="form-group col-md-4"><label>Responsable</label><select name="responsable_id" class="form-control"><option value="">Sin asignar</option>@foreach($usuarios as $u)<option value="{{ $u->id }}" @selected(old('responsable_id')==$u->id)>{{ $u->name }}</option>@endforeach</select></div></div>
    <div class="form-group"><label>Identificación *</label><textarea name="identificacion" class="form-control" rows="3" required placeholder="Ej.: Posible interrupción del servicio por dependencia de un único proveedor">{{ old('identificacion',$contexto?->descripcion) }}</textarea><small class="form-text text-muted">Describí el evento incierto y su causa, sin incluir todavía la acción que se realizará.</small></div>
    <div class="form-row"><div class="form-group col-md-6"><label>Partes afectadas</label><select name="partes_interesadas_seleccion[]" class="form-control" multiple size="6" data-other-target="riesgoPartesOtro">@foreach($partesCatalogo as $parte)<option value="{{ $parte }}" @selected(in_array($parte,old('partes_interesadas_seleccion',[])))>{{ $parte }}</option>@endforeach<option value="__otro__" @selected(in_array('__otro__',old('partes_interesadas_seleccion',[])))>Otra</option></select><div id="riesgoPartesOtro" class="mt-2 d-none"><input name="partes_interesadas_otro" class="form-control" value="{{ old('partes_interesadas_otro') }}" placeholder="Escribí otra parte afectada"></div><small class="form-text text-muted">Podés seleccionar varias manteniendo presionada la tecla Ctrl. Indicá quién podría verse beneficiado o perjudicado.</small></div><div class="form-group col-md-6"><label>Efecto potencial *</label><textarea name="efecto_potencial" class="form-control" rows="3" required placeholder="Ej.: Indisponibilidad del servicio para clientes y demora en la atención">{{ old('efecto_potencial') }}</textarea><small class="form-text text-muted">Explicá la consecuencia posible sobre clientes, calidad, plazos, costos o resultados.</small></div></div>
    <div class="form-row"><div class="form-group col-md-3"><label>Gravedad / beneficio *</label><select name="impacto_inicial" class="form-control" required>@foreach([1=>'1 — Bajo',2=>'2 — Medio',3=>'3 — Alto'] as $n=>$etiqueta)<option value="{{ $n }}" @selected(old('impacto_inicial')==$n)>{{ $etiqueta }}</option>@endforeach</select><small class="form-text text-muted">Magnitud del perjuicio o beneficio esperado.</small></div><div class="form-group col-md-3"><label>Probabilidad *</label><select name="probabilidad_inicial" class="form-control" required>@foreach([1=>'1 — Poco probable',2=>'2 — Posible',3=>'3 — Probable'] as $n=>$etiqueta)<option value="{{ $n }}" @selected(old('probabilidad_inicial')==$n)>{{ $etiqueta }}</option>@endforeach</select><small class="form-text text-muted">Posibilidad de que el evento ocurra.</small></div><div class="form-group col-md-3"><label>Verificación prevista</label><input type="date" name="fecha_verificacion_prevista" value="{{ old('fecha_verificacion_prevista') }}" class="form-control"><small class="form-text text-muted">Fecha en la que se evaluará si las acciones fueron eficaces.</small></div></div>
    <hr><h2 class="iso-section-title">Acción inicial opcional</h2><p class="text-muted">Puede guardarse el registro sin acción y agregarla después.</p>
    <div class="form-group"><label>Acción / tratamiento</label><textarea name="accion_descripcion" class="form-control" rows="3"></textarea></div><div class="form-row"><div class="form-group col-md-6"><label>Responsable de la acción</label><select name="accion_responsable_id" class="form-control"><option value="">Seleccionar</option>@foreach($usuarios as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div class="form-group col-md-3"><label>Fecha objetivo</label><input type="date" name="accion_fecha_objetivo" class="form-control"></div></div>
</div><div class="iso-panel-header justify-content-end"><button class="btn btn-primary">Crear registro</button></div></form></div>
@include('iso._guided_fields')
@endsection
