@extends('layouts.main')
@include('iso._styles')
@section('heading','Detalle de riesgo u oportunidad')
@section('contenidoPrincipal')
<div class="iso-shell">@include('iso._alerts')<a href="{{ route('planificacion.riesgos.index',['periodo'=>$riesgo->periodo_id]) }}">← Volver</a>
<div class="iso-toolbar"><div><div class="iso-code">{{ $riesgo->codigo }}</div><h1 class="iso-title">{{ ucfirst($riesgo->tipo) }}</h1><p class="iso-subtitle">{{ $riesgo->identificacion }}</p></div><div class="text-right"><span class="iso-status {{ $riesgo->indice_inicial>6?'danger':($riesgo->indice_inicial>=3?'warn':'ok') }}">Índice inicial {{ $riesgo->indice_inicial }}</span><div class="mt-2">{{ ucfirst(str_replace('_',' ',$riesgo->estado)) }}</div></div></div>
<div class="iso-panel mb-4"><div class="iso-panel-body iso-detail-grid"><div class="iso-field"><label>Origen</label><div>@if($riesgo->contexto)<a href="{{ route('planificacion.foda.show',$riesgo->contexto) }}">{{ $riesgo->contexto->codigo }} — {{ $riesgo->contexto->titulo }}</a>@else Registro independiente @endif</div></div><div class="iso-field"><label>Proceso</label><div>{{ $riesgo->proceso }}</div></div><div class="iso-field"><label>Efecto potencial</label><div>{{ $riesgo->efecto_potencial }}</div></div><div class="iso-field"><label>Responsable</label><div>{{ $riesgo->responsable?->name ?: 'Sin asignar' }}</div></div></div></div>
<div class="row"><div class="col-lg-7 mb-4"><div class="iso-panel"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Acciones y evidencias</h2></div><div class="iso-panel-body">
@forelse($riesgo->acciones as $accion)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>{{ $accion->descripcion }}</strong><span class="iso-status">{{ ucfirst(str_replace('_',' ',$accion->estado)) }}</span></div><small class="text-muted">{{ $accion->responsable?->name }} · Objetivo {{ $accion->fecha_objetivo?->format('d/m/Y') }}</small>
@foreach($accion->seguimientos as $s)<div class="mt-3 pl-3 border-left"><strong>{{ $s->fecha->format('d/m/Y') }}</strong> — {{ $s->detalle }}@if($s->resultado)<div><em>Resultado: {{ $s->resultado }}</em></div>@endif @if($s->documento)<div><a href="{{ route('documentos.validaPermiso',['id'=>$s->documento->id,'ruta'=>'documentos.show','permiso'=>'puedeLeer']) }}">Documento SGD: {{ $s->documento->titulo }}</a></div>@endif @if($s->enlace_externo)<div><a href="{{ $s->enlace_externo }}" target="_blank" rel="noopener">Evidencia externa</a></div>@endif</div>@endforeach
@if(auth()->user()->puedeGestionarPlanificacion())<hr><form method="POST" action="{{ route('planificacion.acciones.seguimientos.store',$accion) }}">@csrf<div class="form-row"><div class="form-group col-md-4"><input type="date" name="fecha" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group col-md-8"><input name="detalle" class="form-control" placeholder="Seguimiento o verificación realizada" required></div></div><div class="form-row"><div class="form-group col-md-5"><select name="documento_id" class="form-control"><option value="">Sin documento del SGD</option>@foreach($documentos as $d)<option value="{{ $d->id }}">{{ $d->titulo }}</option>@endforeach</select></div><div class="form-group col-md-5"><input type="url" name="enlace_externo" class="form-control" placeholder="https://... evidencia externa"></div><div class="col-md-2"><button class="btn btn-outline-primary btn-block">Agregar</button></div></div></form>
<form method="POST" action="{{ route('planificacion.acciones.actualizar',$accion) }}" class="form-inline">@csrf @method('PATCH')<select name="estado" class="form-control form-control-sm mr-2">@foreach(['pendiente','en_proceso','completada','cancelada'] as $e)<option value="{{ $e }}" @selected($accion->estado===$e)>{{ ucfirst(str_replace('_',' ',$e)) }}</option>@endforeach</select><input name="resultado" value="{{ $accion->resultado }}" class="form-control form-control-sm mr-2" placeholder="Resultado"><button class="btn btn-sm btn-secondary">Actualizar</button></form>@endif
</div>@empty<p class="text-muted">No hay acciones registradas.</p>@endforelse
@if(auth()->user()->puedeGestionarPlanificacion())<hr><h3 class="h6 font-weight-bold">Agregar acción</h3><form method="POST" action="{{ route('planificacion.acciones.store',$riesgo) }}">@csrf<div class="form-group"><textarea name="descripcion" class="form-control" rows="2" placeholder="Acción concreta y verificable" required></textarea></div><div class="form-row"><div class="col-md-6"><select name="responsable_id" class="form-control" required><option value="">Responsable</option>@foreach($usuarios as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div class="col-md-4"><input type="date" name="fecha_objetivo" class="form-control" required></div><div class="col-md-2"><button class="btn btn-primary btn-block">Agregar</button></div></div></form>@endif
</div></div></div>
<div class="col-lg-5 mb-4"><div class="iso-panel"><div class="iso-panel-header"><h2 class="iso-section-title mb-0">Verificación de eficacia</h2></div><div class="iso-panel-body">
@if(auth()->user()->puedeGestionarPlanificacion())<form method="POST" action="{{ route('planificacion.riesgos.verificar',$riesgo) }}">@csrf @method('PATCH')<div class="form-group"><label>Conclusión y evidencia *</label><textarea name="conclusion_eficacia" class="form-control" rows="5" required>{{ $riesgo->conclusion_eficacia }}</textarea></div><div class="form-row"><div class="form-group col-4"><label>Eficacia</label><select name="eficacia" class="form-control">@foreach(['si'=>'Sí','parcial'=>'Parcial','no'=>'No'] as $v=>$l)<option value="{{ $v }}" @selected($riesgo->eficacia===$v)>{{ $l }}</option>@endforeach</select></div><div class="form-group col-4"><label>G/B final</label><select name="impacto_final" class="form-control">@foreach([1,2,3] as $n)<option @selected($riesgo->impacto_final===$n)>{{ $n }}</option>@endforeach</select></div><div class="form-group col-4"><label>P final</label><select name="probabilidad_final" class="form-control">@foreach([1,2,3] as $n)<option @selected($riesgo->probabilidad_final===$n)>{{ $n }}</option>@endforeach</select></div></div><div class="form-group"><label>Estado resultante</label><select name="estado" class="form-control"><option value="en_proceso">En proceso</option><option value="permanente">Permanente</option><option value="finalizado">Finalizado</option></select></div><button class="btn btn-primary">Registrar verificación</button></form>@else<p>{{ $riesgo->conclusion_eficacia ?: 'Pendiente' }}</p>@endif
</div></div></div></div></div>
@endsection
